[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

# Live config reload (changes require restart)
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
# family = "MesloLGS Nerd Font Mono"
# family = "CaskaydiaCove Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
# family = "CaskaydiaCove Nerd Font"
# family = "MesloLGS Nerd Font Mono"
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
# family = "CaskaydiaCove Nerd Font"
# family = "MesloLGS Nerd Font Mono"
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
# family = "MesloLGS Nerd Font Mono"
#family = "CaskaydiaCove Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Regular"


